### ISSUE TITLE
Source .env configuration from a string parameter.

### ISSUE THREAD

**Issue by arrterian** [nsaunders/purescript-dotenv#32]
Hi,
It's a very useful package in purescript registry. Thanks for creating that staff.
But I pay attention to the lack of exposed API methods for working with input (expect loadFile).

I think it will be useful to add a method like this

```purescript
readEnvSrting :: String -> Either ParseError Settings
```

What do you think about the idea guys?

**Comment by nsaunders** [comment]
Hi @arrterian and thanks for your interest. I appreciate any suggestions about API design, but I want to make sure I am understanding your request properly. In your proposed `readEnvString` function, what is represented by the `String` input?

**Comment by arrterian** [comment]
@nsaunders  Exactly. For cases when we already read our file into a string and need to make just parse operation. After all, it allows us to read config from different sources. From external URL or whatever.

**Comment by arrterian** [comment]
After all, it allows us to read config from different sources. From external URL or whatever.

**Comment by nsaunders** [comment]
Thanks for clarifying, @arrterian. I thought that was likely the case, but I wanted to make sure.

Due to [variable substitution](https://github.com/nsaunders/purescript-dotenv#variable-substitution) and [command substitution](https://github.com/nsaunders/purescript-dotenv#command-substitution), the result of `readEnvString` would not be as simple as [`Either ParseError Settings`](https://pursuit.purescript.org/packages/purescript-dotenv/1.0.0/docs/Dotenv#t:Settings). Rather, the result of the [main parsing function (`settings`)](https://pursuit.purescript.org/packages/purescript-dotenv/1.0.0/docs/Dotenv.Internal.Parse#v:settings) is an [`Array (Setting UnresolvedValue)`](https://pursuit.purescript.org/packages/purescript-dotenv/1.0.0/docs/Dotenv.Internal.Types#t:UnresolvedValue). Additional side effects must be run to turn this into `Settings`.

Understanding this, do you still feel that the parsing logic is independently useful? If so, it would be great to have a few more details about your use case, if you have anything more to say about it. Thanks in advance!

**Comment by arrterian** [comment]
It will be useful anyway. I'll share my case.
I start rewriting codebase for my [extension](https://github.com/arrterian/nix-env-selector/blob/master/src/env.ts) from TypeScript to purescript. For now, I obtained the current env variables by spawning command `nix-shell --run env`. The command returns .dotenv compatible string with all environment variables. I need to parse the variables and set for the current VS Code extension host process.

**Comment by arrterian** [comment]
So, I want to parse the input from a string rather than a file. If we need additional side effect it's ok.

BTW: It's my first project on PureScript, and if you find some mistakes in my reasoning, please, let me know.

**Comment by nsaunders** [comment]
Thanks, @arrterian, this makes complete sense. I think this is the API we want: `loadFileContents :: String -> Aff Settings`. Other than accepting the .env content as input, it will work the same as the existing `loadFile`. Please let me know if I have misunderstood; otherwise, I should be able to help out with this pretty soon.

**Comment by arrterian** [comment]
@nsaunders You understood everything right. One notice. I think that the name `loadFileContents` it's a little confusing. Because the method doesn't work with a file. Do you consider the name `loadContents` instead? With type declaration, the name provides a better understanding of how we can use it.

**Comment by nsaunders** [comment]
Awesome, I struggled with the name a bit, but `loadContents` makes good sense to me. Thanks for your input!

**Comment by nsaunders** [comment]
@arrterian I have released v1.1.0 which includes the new `loadContents` function. I think this will automatically be updated in package-sets, but I will verify in a day or two.

**Comment by arrterian** [comment]
Awesome. Thank you a lot)
